name: Release nwipe-static workflow

on:
  push:
    tags:
      - 'nwipe-static*'

jobs:
  build-nwipe-static:
    strategy:
      matrix:
        arch: [amd64,arm64]
    uses: ./.github/workflows/build_nwipe-static_base_workflow.yml
    with:
      arch: ${{ matrix.arch }}

  release-nwipe-static:
    runs-on: ubuntu-latest
    needs: [build-nwipe-static]
    strategy:
      matrix:
        arch: [amd64,arm64]
    env:
      NWIPE_VERSION: 0.38
    steps:
      # Checkout the repository, this is needed for 'gh' to work
      - uses: actions/checkout@v4.1.6

      - name: Download nwipe-static release files
        uses: actions/download-artifact@v4.1.7
        with:
          name: nwipe-static-${{ env.NWIPE_VERSION }}-${{ matrix.arch }}.tar.xz

      - name: Create nwipe-static Release
        id: create_release
        run: |
          tag_name=$(echo "${GITHUB_REF#refs/tags/}")
          body="Release notes for $tag_name - ${{ matrix.arch }}"
          release_tag="${tag_name}-${{ matrix.arch }}"

          echo "Creating release $release_tag"
          gh release create "$release_tag" "nwipe-static-${{ env.NWIPE_VERSION }}-${{ matrix.arch }}.tar.xz" --notes "$body"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Release
        run: |
          tag_name=$(echo "${GITHUB_REF#refs/tags/}")
          release_tag="${tag_name}-${{ matrix.arch }}"
          release_id=$(gh release view "$release_tag" --json id -q ".id")
          echo "Release ID: $release_id"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
